typesConfigurations:
  - typeConfiguration: "CBLCICSDB2"
    variables:
      - name: "compileParms"
        value: "LIB,SOURCE,CICS,SQL"
      - name: "IS_CICS"
        value: "true"
      - name: "IS_SQL"
        value: "true"
      - name: "doLinkEdit"
        value: "false"
  - typeConfiguration: "PLICICS"
    variables:
      - name: "compileParms"
        value: "PP(INCLUDE('ID(++INCLUDE)'))"
      - name: "doLinkEdit"
        value: "true"
      - name: "IS_CICS"
        value: "true"
